<section>
    
    <div class="row">
        <div class="col-lg-2">
            <div class="fb-like" data-href="https://www.facebook.com/N%C3%A3o-Presta-1150603768305610/" data-layout="button_count" data-action="like" data-show-faces="false" data-share="true"></div>
        </div>
    </div>
    
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 text-center">
            <h5>
                Neste portal você fica sabendo se o produto que pensa em comprar 
                vale a pena e caso tenha comprado algum produto que não prestou 
                você pode deixar registrado aqui.
            </h5>
            <hr />
        </div>
    </div> 
    
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
            <h4>
                Pensa em comprar um produto? veja aqui se ele presta!
            </h4>
            <div class="panel panel-default">
                <div class="panel-heading">Pesquise Se Presta</div>
                <div class="panel-body">
                    <?php echo $this->formSitePesquisa; ?>
                </div>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
            <h4>
                Comprou um produto ruim? Informe que ele não presta!
            </h4>
            <div class="panel panel-default">
                <div class="panel-heading">Isso Não Presta</div>
                <div class="panel-body">
                    <?php echo $this->formSiteNaoPresta; ?>
                </div>
            </div>
        </div>
    </div> 
    
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <h3><?php echo $this->translate("Piores do mercado"); ?></h3><hr />
        </div>
    </div>
    <div class="row">
    <?php if ($this->produtos->count() > 0) : ?>            
        <?php foreach ($this->produtos as $produto) : ?>
        <div class="col-lg-3">        
            <div class="panel panel-default">
                <div class="panel-heading">
                    <?php echo $produto->produto_nome; ?>
                </div>
                <div class="panel-body">
                    <p class="text-center">Taxa de Rejeição</p>
                    <h1 class="text-center">                    
                        <span class="text-danger">                        
                            <i class="fa fa-thumbs-o-down"></i> <?php echo $this->avaliacao($produto->produto_id); ?>%
                        </span>                
                    </h1>
                    <?php $plural = $produto->reclamacoes > 1 ? 'reclamações' : 'reclamação'; ?>
                    <p class="text-center"><?php echo $produto->reclamacoes . ' ' . $plural; ?></p>                    
                    <!--<p class="small text-center"><a href="">Ver reclamações</a></p>-->
                </div>
                <div class="panel-body text-center">
                    <a href="<?php echo $this->url(array(
                        'module' => 'site',
                        'controller' => 'reclamacao',
                        'action' => 'index',
                        'produto' => $produto->produto_id
                    )); ?>" class="btn btn-warning">Registrar Reclamação</a>
                </div>
            </div>
        </div>
        <?php endforeach; ?>            
    <?php else : ?>        
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div class="alert alert-warning">Nenhum registro</div>
        </div>
    <?php endif; ?>
    </div>
    
    <div class="row">
        <div class="col-lg-8"><hr /></div>
    </div>
    
</section>
