<div class="row">
    <div class="col-lg-12">
        <h5>Resultado para: <?php echo $this->produto_pesquisa; ?></h5>        
    </div>
</div>
<?php if ($this->produto_pesquisa && $this->produtos->count() > 0) : ?>
<div class="row">
    <?php foreach ($this->produtos as $produto) : ?>
    <div class="col-lg-3">        
        <div class="panel panel-default">
            <div class="panel-heading">
                <?php echo $produto->produto_nome; ?>
            </div>
            <div class="panel-body">
                <p class="text-center">Taxa de Rejeição</p>
                <h1 class="text-center">                    
                    <span class="text-danger">                        
                        <i class="fa fa-thumbs-o-down"></i> <?php echo $this->avaliacao($produto->produto_id); ?>%
                    </span>                
                </h1>
                <?php $plural = $produto->reclamacoes > 1 ? 'reclamações' : 'reclamação'; ?>
                <p class="text-center"><?php echo $produto->reclamacoes . ' ' . $plural; ?></p>                   
                <!--<p class="small text-center"><a href="">Ver reclamações</a></p>-->
            </div>
            <div class="panel-body text-center">
                <a href="<?php echo $this->url(array(
                    'module' => 'site',
                    'controller' => 'reclamacao',
                    'action' => 'index',
                    'produto' => $produto->produto_id
                )); ?>" class="btn btn-warning">Registrar Reclamação</a>
            </div>
        </div>
    </div>
    <?php endforeach; ?>
</div>
<?php else : ?>
<div class="row">
    <div class="col-lg-12">
        <div class="alert alert-warning alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            <h4><strong>Desculpe,</strong></h4>
            <p>Não encontramos nenhum produto relacionado à sua busca!</p>
            <hr />
            <p>
                <a href="<?php echo $this->url(array(                        
                    'controller' => 'reclamacao',
                    'action' => 'index'
                ), null, true); ?>" class="btn btn-lg btn-danger">RECLAMAR</a>
            </p>
        </div>              
    </div>
</div>
<?php endif; ?>
