<div class="row">
    <div class="col-lg-12">
        <h5>Resultado para: <?php echo $this->produto_pesquisa; ?></h5>        
    </div>
</div>
<?php if ($this->produto_pesquisa && $this->produtos->count() > 0) : ?>
<div class="row">
    <?php foreach ($this->produtos as $produto) : ?>
    <div class="col-lg-3">        
        <div class="panel panel-default">
            <div class="panel-heading">
                <?php echo $produto->produto_nome; ?>
            </div>
            <div class="panel-body">
                <h1 class="text-center">                    
                    <span class="text-danger"><i class="fa fa-thumbs-o-down"></i> 80%</span>
                    <a href=""><i class="fa fa-eye"></i></a>
                </h1>
                <p class="small text-center">XX reclamações</p>
            </div>
            <div class="panel-body text-center">
                <a href="<?php echo $this->url(array(
                    'module' => 'site',
                    'controller' => 'reclamacao',
                    'action' => 'index',
                    'produto' => $produto->produto_id
                )); ?>" class="btn btn-warning">Registrar Reclamação</a>
            </div>
        </div>
    </div>
    <?php endforeach; ?>
</div>
<?php else : ?>
<div class="row">
    <div class="col-lg-12">
        <div class="alert alert-warning alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            <h4><strong>Desculpe,</strong></h4>
            <p>Não encontramos nenhum produto relacionado à sua busca!</p>
            <p>
                <a href="<?php echo $this->url(array(                        
                    'controller' => 'reclamacao',
                    'action' => 'index'
                ), null, true); ?>" class="btn btn-lg btn-danger">RECLAMAR</a>
            </p>
        </div>              
    </div>
</div>
<?php endif; ?>
