<div class="row">
    <div class="col-lg-4 col-lg-offset-2">
        <h3>Faça contato</h3>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-lg-offset-2">
        <p>
            Preencha os campos do formulário e em breve teremos o prazer em 
            lhe responder.
        </p>
        <p>
            A direção.
        </p>
    </div>
    <div class="col-lg-4">
        <div class="panel panel-default">
            <div class="panel-body">
                <?php echo $this->formContato; ?>
            </div>
        </div>        
    </div>
</div>

