<footer class="small">
    <div class="container-fluid container-footer">
        <div class="row">
            <div class="col-md-6">
                <a href="<?php echo $this->url(array(
                    'controller' => 'politica'
                ), null, true); ?>" class="">Política de Privacidade</a>                        
                <a href="<?php echo $this->url(array(
                    'controller' => 'termo'
                ), null, true); ?>" class="">Termo de Uso</a>                        
            </div>
            <div class="col-md-6 text-right">
                <?php echo $this->translate("Todos os direitos reservados"); ?>
            </div>                    
        </div>
    </div>
</footer>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/pt_BR/sdk.js#xfbml=1&version=v2.5&appId=420198398153392";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>