<?php if ($this->produtos && $this->produtos->count() > 0) : ?>
<div class="row">
    <?php foreach ($this->produtos as $produto) : ?>
    <div class="col-lg-3">        
        <div class="panel panel-default">
            <div class="panel-heading">
                <?php echo $produto->produto_nome; ?>
            </div>
            <div class="panel-body">
                <h1 class="text-center">                    
                    <span class="text-danger"><i class="fa fa-thumbs-o-down"></i> 80%</span>
                    <a href=""><i class="fa fa-eye"></i></a>
                </h1>
                <p class="small text-center">XX reclamações</p>
            </div>
            <div class="panel-body text-center">
                <a href="<?php echo $this->url(array(
                    'module' => 'site',
                    'controller' => 'reclamacao',
                    'action' => 'index',
                    'produto' => $produto->produto_id
                )); ?>" class="btn btn-warning">Registrar Reclamação</a>
            </div>
        </div>
    </div>
    <?php endforeach; ?>
</div>
<?php else : ?>
    <?php if ($this->msg && !$this->produto_nome) : ?>
    <div class="row">
        <div class="col-lg-12">
            <div class="alert alert-warning alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4><strong>Desculpe,</strong></h4>
                <p>Não encontramos nenhum produto relacionado à sua busca!</p>
                <p>Preencha o formulário abaixo para registrar sua reclamação.</p>
            </div>              
        </div>
    </div>
    <?php endif; ?>
<div class="row">
    <form method="<?php echo $this->formSiteReclamacao->getMethod(); ?>" action="<?php echo $this->url(array("module" => "", "controller" => "reclamacao", "action" => "reclamar")); ?>">
        <div class="col-lg-4">
            <div class="panel panel-default">
                <div class="panel-heading"><span class="badge">1</span> Informações do Produto</div>
                <div class="panel-body">                                    
                    <?php echo $this->formSiteReclamacao->produto_nome; ?>   
                    <span class="small text-muted">Ex.: Celular Moto E 2ª Geração</span>
                    <?php echo $this->formSiteReclamacao->fabricante_nome; ?>   
                    <span class="small text-muted">Ex.: Motorola</span>
                    <?php echo $this->formSiteReclamacao->marca_nome; ?>   
                    <span class="small text-muted">Ex.: Motorola</span>
                </div>
            </div>        
        </div>
        <div class="col-lg-4">
            <div class="panel panel-default">
                <div class="panel-heading"><span class="badge">2</span> Reclamação</div>
                <div class="panel-body">
                    <?php echo $this->formSiteReclamacao->reclamacao_empresa; ?> 
                    <?php echo $this->formSiteReclamacao->reclamacao_descricao; ?>  
                    <div class="small text-muted text-right" id="limit-char"></div>
                    <?php echo $this->formSiteReclamacao->reclamacao_nota; ?>                  
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="panel panel-default">
                <div class="panel-heading"><span class="badge">3</span> Identificação</div>
                <div class="panel-body">
                    <p class="small text-muted">
                        Sua identificação é muito importante para podermos 
                        ter dados demográficos sólidos e para que a empresa
                        possa enviar uma resposta.
                    </p>
                    <?php echo $this->formSiteReclamacao->reclamacao_nome; ?> 
                    <?php echo $this->formSiteReclamacao->reclamacao_email; ?> 
                    <?php echo $this->formSiteReclamacao->reclamacao_cidade; ?> 
                    <?php echo $this->formSiteReclamacao->reclamacao_estado; ?> 
                    <?php echo $this->formSiteReclamacao->submit; ?> 
                    <?php echo $this->formSiteReclamacao->produto_id; ?> 
                    <?php echo $this->formSiteReclamacao->marca_id; ?> 
                    <?php echo $this->formSiteReclamacao->fabricante_id; ?> 
                </div>
            </div>
        </div>
    </form>
</div>

<?php endif; ?>