<?php echo $this->doctype(); ?>
<?php
    $frontController = Zend_Controller_Front::getInstance()->getRequest();
    $module = $frontController->getModuleName();
    $controller = $frontController->getControllerName();
?>      
<html lang="en">
    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>Não Presta!!</title>

        <link rel="shortcut icon" href="<?php echo $this->baseUrl('views/img/logo.ico'); ?>" />
        
        <!-- CSS -->
        <link href="<?php echo $this->baseUrl("views/css/bootstrap.min.css"); ?>" rel="stylesheet">        
        <link href="<?php echo $this->baseUrl("views/css/bootstrap-theme.min.css"); ?>" rel="stylesheet">
        <!-- Custom Fonts -->
        <link href="<?php echo $this->baseUrl("views/css/font-awesome.min.css"); ?>" rel="stylesheet" type="text/css">  
        <link href="<?php echo $this->baseUrl("views/css/style.css"); ?>" rel="stylesheet">

        <!-- Js -->
        <script src="<?php echo $this->baseUrl("views/js/jquery.min.js"); ?>"></script>
        <script src="<?php echo $this->baseUrl("views/js/bootstrap.min.js"); ?>"></script>
        <script src="<?php echo $this->baseUrl("views/js/jquery.mockjax.js"); ?>"></script>
        <script src="<?php echo $this->baseUrl("views/js/layout.js"); ?>"></script>  
        <script src="<?php echo $this->baseUrl("views/js/jquery.autocomplete.js"); ?>"></script>        

        <?php echo $this->headScript(); ?>

    </head>
    <body>
        <?php echo $this->partial('partials/menu.phtml'); ?>
        <div class="container" id="content">
            
            <!-- PESQUISA E BOTAO RECLAMAR -->
            <?php if ($module === 'site' && $controller !== 'index') : ?>
            <div class="row">
                <div class="col-lg-12 text-right">
                    <form class="form-inline" id="form-site-pesquisa" method="post" action="<?php echo $this->url(array("controller" => "pesquisa"), null, true); ?>">
                        <div class="form-group">
                            <input type="text" name="produto_pesquisa" class="form-control" id="produto_pesquisa" placeholder="Digite o produto">
                        </div>
                        <button type="submit" class="btn btn-success"><i class="fa fa-search"></i> Pesquisar</button>
                    </form>
                </div>
                <!--
                <div class="col-lg-2 text-right">
                    <a href="<?php echo $this->url(array(                        
                        'controller' => 'reclamacao',
                        'action' => 'index'
                    ), null, true); ?>" class="btn btn-lg btn-danger">RECLAMAR</a>
                </div>
                -->
                <div class="col-lg-12"><hr /></div>
            </div>
            <?php endif; ?>
            <!-- Messages -->
            <?php echo $this->messages; ?>
            <?php echo $this->layout()->content; ?>            
        </div> <!-- /container -->    
        <?php echo $this->partial('partials/footer.phtml'); ?>
        <?php echo $this->inlineScript() ?>
    </body>
</html>


